# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c3713a6c703ef9752bf716e461a273a75e4427b24df997425a2eb58ac1a88fe61195865a5f0a1add9472edde8bd9252e81247e849ca7ffdcca82b7f76abe751e

test:
  secret_key_base: c8a216dba24f577a3c384458c315967efcee061224c96a9b8b21a6b16de57a7d1a579ded8b33cd4835c63e9eeb41e027168e5a39cb7981b43bebd2005e8893b5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
